### ISSUE TITLE
Request for Access to BMCD-FGCD Dataset for Research Purposes

### ISSUE THREAD

**Issue by Hassan-Mef** [JustlfC03/SCKansformer#2]
Hello,

I hope this message finds you well.

I am writing to request access to the Bone Marrow Cell Dataset for Fine-Grained Classification (BMCD-FGCD) as mentioned in your repository. A friend of mine is currently working on a research project related to Explainable ensemble deep learning for bone marrow cell classification, and I believe that your dataset would be incredibly valuable for their work.

I have read the README file and understand that the dataset is private and requires proper citation. I assure you that the dataset will be used responsibly and cited as per the guidelines provided.

Could you please provide me with the necessary steps or permissions to access the BMCD-FGCD dataset on behalf of my friend? or If you prefer, you can directly contact my friend for further details. Here are their contact details: 

Name : **Shahid Mehmood**
Email : shahidmehmood.bulc@bahria.edu.pk

Thank you for your time and consideration

**Comment by JustlfC03** [comment]
Thank you for your interest in our work, our paper has been formally accepted and will be ONLINE in the near future (maybe a week or two), at which time we will make the download link to the dataset publicly available!

**Comment by JustlfC03** [comment]
Thank you for your interest, our paper has been officially accepted by JBHI! We have publicized the download link of our BMCD-FGCD dataset, if you need to use our dataset, please cite our paper as requested. Meanwhile, the dataset can only be used for research purposes, any commercial behavior is prohibited without permission.
